services:
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: yarn start:dev

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data: